# Generated by Django 3.1.1 on 2020-09-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='user',
            new_name='post',
        ),
    ]
